//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Cartilla_Autocontrol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCESO_OBRAS
    {
        public int acceso_id { get; set; }
        public Nullable<int> usuario_id { get; set; }
        public Nullable<int> obra_id { get; set; }
    
        public virtual OBRA OBRA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
