//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Cartilla_Autocontrol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCESO_CARTILLA
    {
        public int acceso_cartilla_id { get; set; }
        public int CARTILLA_cartilla_id { get; set; }
        public int USUARIO_usuario_id { get; set; }
        public bool correo_enviado { get; set; }
    
        public virtual CARTILLA CARTILLA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
