//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Cartilla_Autocontrol.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ACTIVIDAD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACTIVIDAD()
        {
            this.CARTILLA = new HashSet<CARTILLA>();
            this.ITEM_VERIF = new HashSet<ITEM_VERIF>();
        }
    
        public int actividad_id { get; set; }

        [Required(ErrorMessage = "Por favor, ingrese un código")]
        [MaxLength(15, ErrorMessage = "El código de la actividad no puede tener más de 15 caracteres")]
        public string codigo_actividad { get; set; }

        [Required(ErrorMessage = "Por favor, ingrese un nombre")]
        public string nombre_actividad { get; set; }
        public string estado { get; set; }
        public int OBRA_obra_id { get; set; }
    
        public virtual OBRA OBRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARTILLA> CARTILLA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITEM_VERIF> ITEM_VERIF { get; set; }
    }
}
