//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;


namespace Proyecto_Cartilla_Autocontrol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARTILLA_DETALLE_VIEW
    {
    
        public int cartilla_id { get; set; }
        public System.DateTime fecha { get; set; }
        public string observaciones { get; set; }
        public int OBRA_obra_id { get; set; }
        public int ACTIVIDAD_actividad_id { get; set; }
        public int ESTADO_FINAL_estado_final_id { get; set; }
        public Nullable<int> CARTILLA_cartilla_id { get; set; }
        public Nullable<int> detalle_cartilla_id { get; set; }
        public Nullable<bool> estado_otec { get; set; }
        public Nullable<bool> estado_ito { get; set; }
        public Nullable<int> ITEM_VERIF_item_verif_id { get; set; }
        public string INMUEBLE_inmueble_id { get; set; }
    }
}
