//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Cartilla_Autocontrol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_VERIF
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ITEM_VERIF()
        {
            this.DETALLE_CARTILLA = new HashSet<DETALLE_CARTILLA>();
        }
    
        public int item_verif_id { get; set; }
        public string elemento_verificacion { get; set; }
        public string label { get; set; }
        public int ACTIVIDAD_actividad_id { get; set; }
    
        public virtual ACTIVIDAD ACTIVIDAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_CARTILLA> DETALLE_CARTILLA { get; set; }
    }
}
