//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Cartilla_Autocontrol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOTE_INMUEBLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOTE_INMUEBLE()
        {
            this.INMUEBLE = new HashSet<INMUEBLE>();
        }
    
        public int lote_id { get; set; }
        public string tipo_bloque { get; set; }
        public string numero_letra_bloque_1 { get; set; }
        public string abreviatura { get; set; }
        public Nullable<decimal> cantidad_pisos { get; set; }
        public decimal cantidad_inmuebles { get; set; }
        public string descripcion_tipo_proyecto { get; set; }
        public int OBRA_obra_id { get; set; }
        public Nullable<decimal> rango_inicial { get; set; }
        public Nullable<decimal> rango_final { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INMUEBLE> INMUEBLE { get; set; }
        public virtual OBRA OBRA { get; set; }
    }
}
