//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Cartilla_Autocontrol.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ObraManzanoConexion : DbContext
    {
        public ObraManzanoConexion()
            : base("name=ObraManzanoConexion")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACTIVIDAD> ACTIVIDAD { get; set; }
        public virtual DbSet<CARTILLA> CARTILLA { get; set; }
        public virtual DbSet<COMUNA> COMUNA { get; set; }
        public virtual DbSet<DETALLE_CARTILLA> DETALLE_CARTILLA { get; set; }
        public virtual DbSet<ESTADO_FINAL> ESTADO_FINAL { get; set; }
        public virtual DbSet<INMUEBLE> INMUEBLE { get; set; }
        public virtual DbSet<ITEM_VERIF> ITEM_VERIF { get; set; }
        public virtual DbSet<OBRA> OBRA { get; set; }
        public virtual DbSet<PERFIL> PERFIL { get; set; }
        public virtual DbSet<PERSONA> PERSONA { get; set; }
        public virtual DbSet<REGION> REGION { get; set; }
        public virtual DbSet<RESPONSABLE> RESPONSABLE { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    }
}
