//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Cartilla_Autocontrol.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PERSONA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERSONA()
        {
            this.RESPONSABLE = new HashSet<RESPONSABLE>();
            this.USUARIO = new HashSet<USUARIO>();
        }

        [Required(ErrorMessage = "El RUT es obligatorio")]
        [RegularExpression(@"^[0-9]{7,8}-[0-9Kk]$", ErrorMessage = "Formato de RUT inválido")]
        public string rut { get; set; }

        [Required(ErrorMessage = "Por favor, ingrese un nombre")]
        public string nombre { get; set; }

        [Required(ErrorMessage = "Por favor, ingrese apellido paterno")]
        public string apeliido_paterno { get; set; }

        [Required(ErrorMessage = "Por favor, ingrese apellido materno")]
        public string apellido_materno { get; set; }

        [Required(ErrorMessage = "Por favor, ingrese un correo eléctronico")]
        public string correo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESPONSABLE> RESPONSABLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO> USUARIO { get; set; }
    }
}
