//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Cartilla_Autocontrol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaExcel
    {
        public string label { get; set; }
        public string elemento_verificacion { get; set; }
        public Nullable<bool> estado_autocontrol { get; set; }
        public Nullable<bool> estado_ito { get; set; }
        public Nullable<bool> estado_supv { get; set; }
        public Nullable<System.DateTime> fecha_rev { get; set; }
        public string codigo_inmueble { get; set; }
        public int cartilla_id { get; set; }
        public int actividad_id { get; set; }
        public Nullable<System.DateTime> fecha_autocontrol { get; set; }
        public Nullable<System.DateTime> fecha_fto { get; set; }
        public Nullable<System.DateTime> fecha_supv { get; set; }
        public bool tipo_item { get; set; }
    }
}
